version: '3.8'

services:
  availarr:
    container_name: availarr
    image: ematts/availarr:latest
    ports:
      - "8686:8686"
    restart: unless-stopped

    environment:
      - TZ=America/Chicago
      - RESET_TOKEN=my_secure_token_here
    volumes:
      - availarr_config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  availarr_config:
